export default [{
    "Title": "Kangaroo Jack",
    "Year": "2003",
    "Rated": "PG",
    "Released": "17 Jan 2003",
    "Runtime": "89 min",
    "Genre": "Action, Adventure, Comedy",
    "Director": "David McNally",
    "Writer": "Steve Bing (story), Barry O'Brien (story), Steve Bing (screenplay), Scott Rosenberg (screenplay)",
    "Actors": "Jerry O'Connell, Anthony Anderson, Estella Warren, Christopher Walken",
    "Plot": "Two childhood friends, a New York hairstylist and a would-be musician, get caught up with the mob and are forced to deliver $50,000 to Australia, but things go haywire when the money is lost to a wild kangaroo.",
    "Language": "English",
    "Country": "USA, Australia",
    "Awards": "1 win & 5 nominations.",
    "Poster": "http://ia.media-imdb.com/images/M/MV5BMTk1Njg5MjAyOV5BMl5BanBnXkFtZTYwNDAxMDg5._V1_SX300.jpg",
    "Metascore": "16",
    "imdbRating": "4.4",
    "imdbVotes": "21431",
    "imdbID": "tt0257568",
    "Type": "movie",
    "Response": "True"
}, {
    "Title": "When I Grow Up, I'll Be a Kangaroo",
    "Year": "2004",
    "Rated": "N/A",
    "Released": "25 Mar 2004",
    "Runtime": "92 min",
    "Genre": "Comedy",
    "Director": "Radivoje Andric",
    "Writer": "Miroslav Momcilovic",
    "Actors": "Sergej Trifunovic, Marija Karan, Nebojsa Glogovac, Boris Milivojevic",
    "Plot": "The film consists of three parallel stories that are interwoven and played in Vozdovac. In the first story, Braca tries to seduce Iris, a model from the city center. Although they try not ...",
    "Language": "Serbian",
    "Country": "Serbia and Montenegro",
    "Awards": "1 win.",
    "Poster": "N/A",
    "Metascore": "N/A",
    "imdbRating": "8.4",
    "imdbVotes": "5316",
    "imdbID": "tt0383846",
    "Type": "movie",
    "Response": "True"
}, {
    "Title": "Dot and the Kangaroo",
    "Year": "1977",
    "Rated": "N/A",
    "Released": "15 Dec 1977",
    "Runtime": "71 min",
    "Genre": "Animation, Family, Musical",
    "Director": "Yoram Gross",
    "Writer": "Yoram Gross (screenplay), John Palmer (screenplay), Ethel Pedley (book)",
    "Actors": "Barbara Frawley, Joan Bruce, Spike Milligan, June Salter",
    "Plot": "A young girl gets lost in the Australian outback and befriends a kangaroo",
    "Language": "English",
    "Country": "Australia",
    "Awards": "N/A",
    "Poster": "http://ia.media-imdb.com/images/M/MV5BNzgwNjIzMzQ4OV5BMl5BanBnXkFtZTcwMDkzMDIyMQ@@._V1_SX300.jpg",
    "Metascore": "N/A",
    "imdbRating": "7.2",
    "imdbVotes": "494",
    "imdbID": "tt0274470",
    "Type": "movie",
    "Response": "True"
}, {
    "Title": "Kangaroo Jack: G'Day, U.S.A.!",
    "Year": "2004",
    "Rated": "N/A",
    "Released": "16 Nov 2004",
    "Runtime": "75 min",
    "Genre": "Animation, Family",
    "Director": "Ron Myrick",
    "Writer": "Adam Scheinman, Andrew Scheinman",
    "Actors": "Josh Keaton, Ahmed Best, Kath Soucie, Jeff Bennett",
    "Plot": "When poachers kidnap Jackie Legs from the Australian Outback, his friends leap into action! Their attempts to save him route them back to the U.S. into the glitz and glamour of Las Vegas.",
    "Language": "English",
    "Country": "USA",
    "Awards": "N/A",
    "Poster": "http://ia.media-imdb.com/images/M/MV5BMjExODEzODM1NF5BMl5BanBnXkFtZTgwNTU1MDA2MDE@._V1_SX300.jpg",
    "Metascore": "N/A",
    "imdbRating": "4.0",
    "imdbVotes": "168",
    "imdbID": "tt0459425",
    "Type": "movie",
    "Response": "True"
}, {
    "Title": "Kangaroo",
    "Year": "1952",
    "Rated": "NOT RATED",
    "Released": "1 Jun 1952",
    "Runtime": "84 min",
    "Genre": "Adventure, Drama, Western",
    "Director": "Lewis Milestone",
    "Writer": "Martin Berkeley (story), Harry Kleiner",
    "Actors": "Maureen O'Hara, Peter Lawford, Finlay Currie, Richard Boone",
    "Plot": "In turn-of-the-century Australia two criminals ingratiate themselves with a rancher in order to swindle him.However, the two partners become rivals for the affection of the rancher's beautiful daughter.",
    "Language": "English",
    "Country": "USA",
    "Awards": "N/A",
    "Poster": "http://ia.media-imdb.com/images/M/MV5BMTIwMDg1ODE5MV5BMl5BanBnXkFtZTYwMjgwNzg5._V1_SX300.jpg",
    "Metascore": "N/A",
    "imdbRating": "5.5",
    "imdbVotes": "156",
    "imdbID": "tt0044788",
    "Type": "movie",
    "Response": "True"
}, {
    "Title": "Mickey's Kangaroo",
    "Year": "1935",
    "Rated": "N/A",
    "Released": "13 Apr 1935",
    "Runtime": "9 min",
    "Genre": "Animation, Short, Comedy",
    "Director": "David Hand",
    "Writer": "N/A",
    "Actors": "Walt Disney",
    "Plot": "Mickey gets a package from Australia: a kangaroo, complete with boxing gloves. The 'roo moves into Pluto's brand new doghouse, much to his annoyance (which we actually hear voiced). Mickey ...",
    "Language": "English",
    "Country": "USA",
    "Awards": "N/A",
    "Poster": "N/A",
    "Metascore": "N/A",
    "imdbRating": "6.4",
    "imdbVotes": "145",
    "imdbID": "tt0026708",
    "Type": "movie",
    "Response": "True"
}, {
    "Title": "Kangaroo",
    "Year": "1987",
    "Rated": "R",
    "Released": "13 Mar 1987",
    "Runtime": "108 min",
    "Genre": "Drama",
    "Director": "Tim Burstall",
    "Writer": "Evan Jones, D.H. Lawrence (novel)",
    "Actors": "Colin Friels, Judy Davis, John Walton, Julie Nihill",
    "Plot": "A mild-mannered English conscientious objector moves to what he feels will be the relative calm of Australia after World War I, but gets caught in the middle of violent battles between the rising trade unions and fascist groups.",
    "Language": "English",
    "Country": "Australia",
    "Awards": "2 wins & 3 nominations.",
    "Poster": "http://ia.media-imdb.com/images/M/MV5BMjk1MDQ0NTMyNV5BMl5BanBnXkFtZTcwOTIzMzMzMQ@@._V1_SX300.jpg",
    "Metascore": "N/A",
    "imdbRating": "6.7",
    "imdbVotes": "141",
    "imdbID": "tt0091325",
    "Type": "movie",
    "Response": "True"
}, {
    "Title": "Kangaroo Court",
    "Year": "1994",
    "Rated": "N/A",
    "Released": "26 Sep 2001",
    "Runtime": "N/A",
    "Genre": "Short",
    "Director": "Sean Astin",
    "Writer": "Laurence Andries",
    "Actors": "Gregory Hines, Stoney Jackson, Mister Jones, Michael O'Keefe",
    "Plot": "N/A",
    "Language": "English",
    "Country": "USA",
    "Awards": "N/A",
    "Poster": "N/A",
    "Metascore": "N/A",
    "imdbRating": "7.5",
    "imdbVotes": "100",
    "imdbID": "tt0110239",
    "Type": "movie",
    "Response": "True"
}, {
    "Title": "The Kangaroo",
    "Year": "1976",
    "Rated": "N/A",
    "Released": "8 Oct 1976",
    "Runtime": "95 min",
    "Genre": "Comedy",
    "Director": "János Zsombolyai",
    "Writer": "Bulcsú Bertha, Bulcsú Bertha (novel), János Zsombolyai",
    "Actors": "László Gálffi, Éva Vándor, Erzsi Pártos, Dezsõ Füller",
    "Plot": "N/A",
    "Language": "Hungarian",
    "Country": "Hungary",
    "Awards": "N/A",
    "Poster": "N/A",
    "Metascore": "N/A",
    "imdbRating": "6.8",
    "imdbVotes": "71",
    "imdbID": "tt0144267",
    "Type": "movie",
    "Response": "True"
}, {
    "Title": "The Kangaroo",
    "Year": "1976",
    "Rated": "N/A",
    "Released": "8 Oct 1976",
    "Runtime": "95 min",
    "Genre": "Comedy",
    "Director": "János Zsombolyai",
    "Writer": "Bulcsú Bertha, Bulcsú Bertha (novel), János Zsombolyai",
    "Actors": "László Gálffi, Éva Vándor, Erzsi Pártos, Dezsõ Füller",
    "Plot": "N/A",
    "Language": "Hungarian",
    "Country": "Hungary",
    "Awards": "N/A",
    "Poster": "N/A",
    "Metascore": "N/A",
    "imdbRating": "6.8",
    "imdbVotes": "71",
    "imdbID": "tt0144267",
    "Type": "movie",
    "Response": "True"
}];
